### ISSUE TITLE
consider lodash-mixin

### ISSUE THREAD

**Issue by klaemo** [AmpersandJS/ampersand-rest-collection#22]
There's been some discussion around replacing underscore in AmpersandJS/ampersand-collection-underscore-mixin/issues/12.

You might consider https://github.com/klaemo/ampersand-collection-lodash-mixin as a starting point.

I don't think a core ampersand module as this one should depend on underscore, while the rest switches to lodash modules. :)

**Comment by HenrikJoreteg** [comment]
It's all ready for you @klaemo per our twitter conversation: https://github.com/ampersandjs/ampersand-collection-lodash-mixin you should have access. Let me know if you don't, or have questions.

Also, are you opposed to being listed here: http://ampersandjs.com/contribute ?

**Comment by klaemo** [comment]
Thanks, @HenrikJoreteg :) I just pushed the code.

No problem being listed on the website. I'd be an honor :)

**Comment by wraithgar** [comment]
This may be as good a point as any to talk about decoupling the underscore/lodash mixin from everything by default.

**Comment by lukekarrys** [comment]
I think I'm -1 on removing the util mixin (which will now be lodash) from this module for a few reasons. I haven't thought too much about the other modules (which might be totally different cases) but at least for this one here are my thoughts:

1. provides an easier upgrade path from backbone
2. removes at least one step of users having to think about what to install for a "core" set of modules
3. if we do remove it then this module is left to be just extending collection with the rest mixin, which makes it seem like we could almost remove this module altogether. I could almost see that being the case since this module is very simple, but I do like having it around as an opionated-heres-what-to-install-get-started-on-a-standard-project.

**Comment by HenrikJoreteg** [comment]
Agree with @luke. I like having it as a "here's what you'll need most of the time" sort of thing. I see it as a good convenience that eases transitions for people coming from BB.

**Comment by HenrikJoreteg** [comment]
@klaemo published: https://www.npmjs.com/package/ampersand-collection-lodash-mixin `2.0.0`
